In [1]:
import pandas as pd
import numpy as np
import re

In [43]:
pd.set_option('display.max_columns', None)

In [ ]:
df1 = pd.read_csv("aircraft_specs.csv")
df8 = pd.read_csv("extra_aircraft_specs.csv")

In [ ]:
df1.head(3)

,Name,URL,Info_Avionics,Info_Crew,Info_Engine,Info_Engine type,Info_Power,Info_Seats,Info_Thrust,Info_Wing tips,...,Size_Exterior length,Size_Fuselage diameter,Size_Tail height,Size_Wing span,Weight_Empty weight,Weight_Fuel capacity,Weight_Gross weight,Weight_Max landing weight,Weight_Max payload,Weight_Max takeoff weight
0,Airbus A300,https://aerocorner.com/aircraft/airbus-a300-600/,Honeywell 331-250,—,2 × Pratt & Whitney PW4000,Turbofan,NaN,—,"2 × 99,040 lbf · 441 kN",Wingtip fences,...,177 ft 6 in · 54.10 m,18 ft 6 in · 5.64 m,—,147 ft 1 in · 44.84 m,—,"18,000gal·68,100L·54,500kg(Jet A)",—,"304,000 lb · 138,000 kg","120,500 lb · 55,000 kg","364,000 lb · 165,000 kg"
1,Airbus A310,https://aerocorner.com/aircraft/airbus-a310-300/,Honeywell 331-250,—,2 × JT9D-7R4E1 / PW4000 / CF6-80C2,Turbofan,NaN,243,"2 × 62,000 lbf · 276 kN",No winglets,...,153 ft 1 in · 46.66 m,18 ft 4 in · 5.60 m,52 ft 1 in · 15.87 m,144 ft 0 in · 43.90 m,—,"16,150gal·61,100L·48,900kg(Jet A)",—,"273,500 lb · 124,000 kg","76,500 lb · 34,800 kg","361,500 lb · 164,000 kg"
2,Airbus A319,https://aerocorner.com/aircraft/airbus-industr...,Thales D-HUDS Avionics,—,2 × International Aero Engines V2500,Turbofan,NaN,156 economy·124 business,"2 × 23,500 lbf · 105 kN",Wingtip fences,...,111 ft 0 in · 33.84 m,13 ft 0 in · 3.96 m,38 ft 7 in · 11.76 m,111 ft 11 in · 34.10 m,—,"6,300gal·23,900L·19,100kg(Jet A)",—,"138,000 lb · 62,500 kg","30,900 lb · 14,000 kg","166,500 lb · 75,500 kg"

In [6]:
df8.head(3)

,Name,URL,Info_Avionics,Info_Crew,Info_Engine,Info_Engine type,Info_Power,Info_Seats,Info_Thrust,Info_Wing tips,...,Size_Exterior length,Size_Fuselage diameter,Size_Tail height,Size_Wing span,Weight_Empty weight,Weight_Fuel capacity,Weight_Gross weight,Weight_Max landing weight,Weight_Max payload,Weight_Max takeoff weight
0,Bristol 175 Britannia,https://aerocorner.com/aircraft/bristol-britan...,—,—,4 × Bristol Proteus 765,Turboprop,"4 × 4,450 shp · 3,318 kW",146,NaN,No winglets,...,124 ft 3 in · 37.87 m,12 ft 2 in · 3.70 m,37 ft 6 in · 11.43 m,142 ft 3 in · 43.36 m,—,"8,050gal·30,500L·24,400kg(Jet A)",—,—,"61,500 lb · 28,000 kg","185,000 lb · 84,000 kg"
1,Lockheed L-1011 TriStar,https://aerocorner.com/aircraft/lockheed-l-101...,L-1011 Avionics Flight Control System,—,3 × Rolls-Royce RB211-22,Turbofan,NaN,400,"3 × 42,000 lbf · 187 kN",No winglets,...,177 ft 9 in · 54.17 m,19 ft 7 in · 5.97 m,55 ft 4 in · 16.87 m,155 ft 4 in · 47.35 m,—,"26,500gal·100,300L·80,300kg(Jet A)",—,"366,000 lb · 166,000 kg","74,000 lb · 33,700 kg","465,000 lb · 211,000 kg"
2,De Havilland Canada DHC-8 Dash 8,https://aerocorner.com/aircraft/bombardier-q400/,Rockwell Collins Pro Line Fusion,—,—,-,"5,071 hp · 3,781 kW",78 economy·68 business,NaN,No winglets,...,107 ft 9 in · 32.84 m,8 ft 10 in · 2.69 m,—,93 ft 3 in · 28.42 m,—,"1,700gal·6,400L·5,100kg(Jet A)",—,—,"19,100 lb · 8,650 kg","313,500 lb · 142,000 kg"

In [7]:
df1_8 = pd.concat([df1, df8], ignore_index=True)

In [11]:
df1_8["Name"].unique()

array(['Airbus A300', 'Airbus A310', 'Airbus A319', 'Airbus A320',
       'Airbus A321', 'Airbus A330', 'Airbus A340', 'Airbus A350 XWB',
       'Airbus A380', 'Boeing 737', 'Boeing 747', 'Boeing 757',
       'Boeing 767', 'Boeing 777', 'Boeing 787 Dreamliner',
       'Aérospatiale/BAC Concorde', 'McDonnell Douglas DC-10',
       'Convair 880', 'Lockheed L-188 Electra', 'Fokker 50 / 60',
       'McDonnell Douglas MD-80', 'McDonnell Douglas MD-90',
       'Airbus A220', 'Fokker 70 / 100', 'McDonnell Douglas MD-11',
       'Airbus A318', 'Bombardier CRJ-700', 'Bombardier CRJ-900',
       'Bombardier CRJ-1000', 'Convair 990', 'Dornier Do-328',
       'Douglas DC-8', 'Embraer EMB-120 Brasilia', 'Embraer ERJ-145',
       'Embraer ERJ-170', 'Embraer ERJ-190', 'Saab 340', 'Saab 2000',
       'BAC Vickers VC-10', 'Hawker Siddeley HS-121 Trident',
       'Vickers Vanguard', 'Boeing 717', 'Short 330', 'COMAC ARJ21',
       'COMAC C919', 'Canadair CL-44', 'Bristol 175 Britannia',
       'Lockheed L-1011 TriStar', 'De Havilland Canada DHC-8 Dash 8',
       'British Aerospace BAe 146 / Avro RJ', 'McDonnell Douglas DC-9',
       'Bombardier BD-700 Global', 'ATR 42 / 72',
       'British Aerospace BAe ATP'], dtype=object)

In [12]:
df1_8.to_csv("aircraft_specs.csv", encoding='utf-8-sig', index=False)

In [88]:
df1 = pd.read_csv("aircraft_specs.csv")

In [89]:
df1.head()

,Name,URL,Info_Avionics,Info_Crew,Info_Engine,Info_Engine type,Info_Power,Info_Seats,Info_Thrust,Info_Wing tips,Performance_Approach speed,Performance_Ceiling,Performance_Cruise speed,Performance_Fuel burn,Performance_Landing distance,Performance_Max cruise speed,Performance_Maximum speed,Performance_Range,Performance_Rate of climb,Performance_Takeoff distance,Size_Baggage volume,Size_Cabin height,Size_Cabin length,Size_Cabin width,Size_Exterior length,Size_Fuselage diameter,Size_Tail height,Size_Wing span,Weight_Empty weight,Weight_Fuel capacity,Weight_Gross weight,Weight_Max landing weight,Weight_Max payload,Weight_Max takeoff weight
0,Airbus A300,https://aerocorner.com/aircraft/airbus-a300-600/,Honeywell 331-250,—,2 × Pratt & Whitney PW4000,Turbofan,NaN,—,"2 × 99,040 lbf · 441 kN",Wingtip fences,131 kt · 151 mph · 243 km/h,"40,000 ft · 12,200 m",—,—,"5,050 ft · 1,540 m",484 kt · 557 mph · 896 km/h,—,"4,050 nm · 4,660 mi · 7,500 km","3,000 ft/min · 15 m/s","7,800 ft · 2,380 m",—,—,133 ft 6 in · 40.70 m,17 ft 4 in · 5.28 m,177 ft 6 in · 54.10 m,18 ft 6 in · 5.64 m,—,147 ft 1 in · 44.84 m,—,"18,000gal·68,100L·54,500kg(Jet A)",—,"304,000 lb · 138,000 kg","120,500 lb · 55,000 kg","364,000 lb · 165,000 kg"
1,Airbus A310,https://aerocorner.com/aircraft/airbus-a310-300/,Honeywell 331-250,—,2 × JT9D-7R4E1 / PW4000 / CF6-80C2,Turbofan,NaN,243,"2 × 62,000 lbf · 276 kN",No winglets,139 kt · 160 mph · 257 km/h,"41,000 ft · 12,500 m",—,—,"4,900 ft · 1,490 m",482 kt · 555 mph · 893 km/h,—,"5,150 nm · 5,930 mi · 9,540 km","2,500 ft/min · 13 m/s","7,500 ft · 2,290 m","3,962 ft³ · 112.2 m³",7 ft 8 in · 2.33 m,109 ft 1 in · 33.24 m,17 ft 4 in · 5.28 m,153 ft 1 in · 46.66 m,18 ft 4 in · 5.60 m,52 ft 1 in · 15.87 m,144 ft 0 in · 43.90 m,—,"16,150gal·61,100L·48,900kg(Jet A)",—,"273,500 lb · 124,000 kg","76,500 lb · 34,800 kg","361,500 lb · 164,000 kg"
2,Airbus A319,https://aerocorner.com/aircraft/airbus-industr...,Thales D-HUDS Avionics,—,2 × International Aero Engines V2500,Turbofan,NaN,156 economy·124 business,"2 × 23,500 lbf · 105 kN",Wingtip fences,—,"41,000 ft · 12,500 m",—,0.54 nm/gal · 0.26 km/L,"4,750 ft · 1,450 m",514 kt · 592 mph · 952 km/h,—,"3,672 nm · 4,230 mi · 6,800 km","3,500 ft/min · 18 m/s","6,400 ft · 1,950 m",976 ft³ · 27.6 m³,7 ft 3 in · 2.22 m,78 ft 0 in · 23.78 m,12 ft 2 in · 3.70 m,111 ft 0 in · 33.84 m,13 ft 0 in · 3.96 m,38 ft 7 in · 11.76 m,111 ft 11 in · 34.10 m,—,"6,300gal·23,900L·19,100kg(Jet A)",—,"138,000 lb · 62,500 kg","30,900 lb · 14,000 kg","166,500 lb · 75,500 kg"
3,Airbus A320,https://aerocorner.com/aircraft/airbus-a320/,Thales Avionics Suite,—,2 × IAE V2500 or CFM International CFM56-5B,Turbofan,NaN,190 economy·148 business,"2 × 27,000 lbf · 120 kN",Wingtip fences,137 kt · 158 mph · 254 km/h,"39,000 ft · 11,900 m",—,0.45 nm/gal · 0.22 km/L,"5,050 ft · 1,540 m",514 kt · 592 mph · 952 km/h,—,"3,300 nm · 3,800 mi · 6,110 km","2,500 ft/min · 13 m/s","6,900 ft · 2,100 m","1,321 ft³ · 37.4 m³",7 ft 3 in · 2.22 m,90 ft 3 in · 27.50 m,12 ft 2 in · 3.70 m,123 ft 3 in · 37.57 m,13 ft 0 in · 3.95 m,39 ft 8 in · 12.08 m,117 ft 5 in · 35.80 m,—,"7,850gal·29,700L·23,700kg(Jet A)",—,"145,500 lb · 66,000 kg","44,000 lb · 20,000 kg","172,000 lb · 78,000 kg"
4,Airbus A321,https://aerocorner.com/aircraft/airbus-industr...,Thales Avionics Suite,—,—,-,NaN,220 economy·185 business,"56,200 lbf · 250 kN",No winglets,—,"39,000 ft · 11,900 m",—,0.45 nm/gal · 0.22 km/L,"5,050 ft · 1,540 m","542 kt · 624 mph · 1,004 km/h",—,"3,200 nm · 3,680 mi · 5,930 km",12 ft/min · 0 m/s,"5,600 ft · 1,710 m","1,828 ft³ · 51.8 m³",7 ft 3 in · 2.22 m,113 ft 0 in · 34.44 m,12 ft 2 in · 3.70 m,146 ft 0 in · 44.51 m,13 ft 0 in · 3.96 m,—,111 ft 11 in · 34.10 m,—,"7,850gal·29,700L·23,700kg(Jet A)",—,—,"47,900 lb · 21,700 kg","206,000 lb · 93,500 kg"

In [90]:
# 1. SÜTUN ADLARININ STANDARTLAŞDIRILMASI
# Hamısını kiçik hərf edirik və boşluqları alt xətt (_) ilə əvəz edirik
df1.columns = df1.columns.str.lower().str.replace(' ', '_').str.replace('/', '_')

In [91]:
# 2. BOŞ DƏYƏRLƏRİN TƏMİZLƏNMƏSİ
# "—" işarəsini boşluqla əvəz edirik
df1.replace(['—', ''], np.nan, inplace=True)

C:\Users\99455\AppData\Local\Temp\ipykernel_12388\3284721642.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1.replace(['—', ''], np.nan, inplace=True)

In [92]:
df1.head()

,name,url,info_avionics,info_crew,info_engine,info_engine_type,info_power,info_seats,info_thrust,info_wing_tips,performance_approach_speed,performance_ceiling,performance_cruise_speed,performance_fuel_burn,performance_landing_distance,performance_max_cruise_speed,performance_maximum_speed,performance_range,performance_rate_of_climb,performance_takeoff_distance,size_baggage_volume,size_cabin_height,size_cabin_length,size_cabin_width,size_exterior_length,size_fuselage_diameter,size_tail_height,size_wing_span,weight_empty_weight,weight_fuel_capacity,weight_gross_weight,weight_max_landing_weight,weight_max_payload,weight_max_takeoff_weight
0,Airbus A300,https://aerocorner.com/aircraft/airbus-a300-600/,Honeywell 331-250,NaN,2 × Pratt & Whitney PW4000,Turbofan,NaN,NaN,"2 × 99,040 lbf · 441 kN",Wingtip fences,131 kt · 151 mph · 243 km/h,"40,000 ft · 12,200 m",NaN,NaN,"5,050 ft · 1,540 m",484 kt · 557 mph · 896 km/h,NaN,"4,050 nm · 4,660 mi · 7,500 km","3,000 ft/min · 15 m/s","7,800 ft · 2,380 m",NaN,NaN,133 ft 6 in · 40.70 m,17 ft 4 in · 5.28 m,177 ft 6 in · 54.10 m,18 ft 6 in · 5.64 m,NaN,147 ft 1 in · 44.84 m,NaN,"18,000gal·68,100L·54,500kg(Jet A)",NaN,"304,000 lb · 138,000 kg","120,500 lb · 55,000 kg","364,000 lb · 165,000 kg"
1,Airbus A310,https://aerocorner.com/aircraft/airbus-a310-300/,Honeywell 331-250,NaN,2 × JT9D-7R4E1 / PW4000 / CF6-80C2,Turbofan,NaN,243,"2 × 62,000 lbf · 276 kN",No winglets,139 kt · 160 mph · 257 km/h,"41,000 ft · 12,500 m",NaN,NaN,"4,900 ft · 1,490 m",482 kt · 555 mph · 893 km/h,NaN,"5,150 nm · 5,930 mi · 9,540 km","2,500 ft/min · 13 m/s","7,500 ft · 2,290 m","3,962 ft³ · 112.2 m³",7 ft 8 in · 2.33 m,109 ft 1 in · 33.24 m,17 ft 4 in · 5.28 m,153 ft 1 in · 46.66 m,18 ft 4 in · 5.60 m,52 ft 1 in · 15.87 m,144 ft 0 in · 43.90 m,NaN,"16,150gal·61,100L·48,900kg(Jet A)",NaN,"273,500 lb · 124,000 kg","76,500 lb · 34,800 kg","361,500 lb · 164,000 kg"
2,Airbus A319,https://aerocorner.com/aircraft/airbus-industr...,Thales D-HUDS Avionics,NaN,2 × International Aero Engines V2500,Turbofan,NaN,156 economy·124 business,"2 × 23,500 lbf · 105 kN",Wingtip fences,NaN,"41,000 ft · 12,500 m",NaN,0.54 nm/gal · 0.26 km/L,"4,750 ft · 1,450 m",514 kt · 592 mph · 952 km/h,NaN,"3,672 nm · 4,230 mi · 6,800 km","3,500 ft/min · 18 m/s","6,400 ft · 1,950 m",976 ft³ · 27.6 m³,7 ft 3 in · 2.22 m,78 ft 0 in · 23.78 m,12 ft 2 in · 3.70 m,111 ft 0 in · 33.84 m,13 ft 0 in · 3.96 m,38 ft 7 in · 11.76 m,111 ft 11 in · 34.10 m,NaN,"6,300gal·23,900L·19,100kg(Jet A)",NaN,"138,000 lb · 62,500 kg","30,900 lb · 14,000 kg","166,500 lb · 75,500 kg"
3,Airbus A320,https://aerocorner.com/aircraft/airbus-a320/,Thales Avionics Suite,NaN,2 × IAE V2500 or CFM International CFM56-5B,Turbofan,NaN,190 economy·148 business,"2 × 27,000 lbf · 120 kN",Wingtip fences,137 kt · 158 mph · 254 km/h,"39,000 ft · 11,900 m",NaN,0.45 nm/gal · 0.22 km/L,"5,050 ft · 1,540 m",514 kt · 592 mph · 952 km/h,NaN,"3,300 nm · 3,800 mi · 6,110 km","2,500 ft/min · 13 m/s","6,900 ft · 2,100 m","1,321 ft³ · 37.4 m³",7 ft 3 in · 2.22 m,90 ft 3 in · 27.50 m,12 ft 2 in · 3.70 m,123 ft 3 in · 37.57 m,13 ft 0 in · 3.95 m,39 ft 8 in · 12.08 m,117 ft 5 in · 35.80 m,NaN,"7,850gal·29,700L·23,700kg(Jet A)",NaN,"145,500 lb · 66,000 kg","44,000 lb · 20,000 kg","172,000 lb · 78,000 kg"
4,Airbus A321,https://aerocorner.com/aircraft/airbus-industr...,Thales Avionics Suite,NaN,NaN,-,NaN,220 economy·185 business,"56,200 lbf · 250 kN",No winglets,NaN,"39,000 ft · 11,900 m",NaN,0.45 nm/gal · 0.22 km/L,"5,050 ft · 1,540 m","542 kt · 624 mph · 1,004 km/h",NaN,"3,200 nm · 3,680 mi · 5,930 km",12 ft/min · 0 m/s,"5,600 ft · 1,710 m","1,828 ft³ · 51.8 m³",7 ft 3 in · 2.22 m,113 ft 0 in · 34.44 m,12 ft 2 in · 3.70 m,146 ft 0 in · 44.51 m,13 ft 0 in · 3.96 m,NaN,111 ft 11 in · 34.10 m,NaN,"7,850gal·29,700L·23,700kg(Jet A)",NaN,NaN,"47,900 lb · 21,700 kg","206,000 lb · 93,500 kg"

In [93]:
df1.columns

Index(['name', 'url', 'info_avionics', 'info_crew', 'info_engine',
       'info_engine_type', 'info_power', 'info_seats', 'info_thrust',
       'info_wing_tips', 'performance_approach_speed', 'performance_ceiling',
       'performance_cruise_speed', 'performance_fuel_burn',
       'performance_landing_distance', 'performance_max_cruise_speed',
       'performance_maximum_speed', 'performance_range',
       'performance_rate_of_climb', 'performance_takeoff_distance',
       'size_baggage_volume', 'size_cabin_height', 'size_cabin_length',
       'size_cabin_width', 'size_exterior_length', 'size_fuselage_diameter',
       'size_tail_height', 'size_wing_span', 'weight_empty_weight',
       'weight_fuel_capacity', 'weight_gross_weight',
       'weight_max_landing_weight', 'weight_max_payload',
       'weight_max_takeoff_weight'],
      dtype='object')

In [95]:
def simple_extract(text, unit):
    if pd.isna(text):
        return None
    
    text_str = str(text)

    if unit == 'SUM':
        numbers = re.findall(r'(\d+)', text_str)
        if numbers:
            return float(sum(map(int, numbers)))
        return None

    parts = text_str.split('·')
    
    for part in parts:
        part = part.strip()
        
        if unit.lower() in part.lower():
            try:
                # A. Vahidin başladığı yeri tapırıq
                index = part.lower().find(unit.lower())
                
                # B. Mətni həmin yerə qədər kəsirik
                before_unit = part[:index]
                
                # C. Boşluqlara bölüb sonuncu rəqəmi götürürük
                words = before_unit.split()
                
                if words:
                    last_word = words[-1]
                    
                    # D. Təmizlik (Vergül, x, × silirik)
                    clean = last_word.replace(',', '').replace('×', '').replace('x', '')
                    
                    return float(clean)
                    
            except (ValueError, IndexError):
                continue 
                
    return None

In [96]:
# Çəki (Weight)
weight_cols = ['weight_gross_weight', 'weight_max_takeoff_weight', 'weight_max_landing_weight', 'weight_max_payload']
for col in weight_cols:
    df1[f'{col}_kg'] = df1[col].apply(lambda x: simple_extract(x, 'kg'))
    df1[f'{col}_lb'] = df1[col].apply(lambda x: simple_extract(x, 'lb'))

In [97]:
# Məsafə (Range)
dist_cols = ['performance_range', 'performance_landing_distance', 'performance_takeoff_distance', 'performance_ceiling']
for col in dist_cols:
    if col in df1.columns:
        df1[f'{col}_m'] = df1[col].apply(lambda x: simple_extract(x, 'm'))
        df1[f'{col}_mi'] = df1[col].apply(lambda x: simple_extract(x, 'mi'))
        df1[f'{col}_km'] = df1[col].apply(lambda x: simple_extract(x, 'km'))
        df1[f'{col}_nm'] = df1[col].apply(lambda x: simple_extract(x, 'nm'))
        df1[f'{col}_ft'] = df1[col].apply(lambda x: simple_extract(x, 'ft'))

In [98]:
# Sürət (Speed)
speed_cols = ['performance_approach_speed', 'performance_cruise_speed', 'performance_max_cruise_speed', 'performance_maximum_speed']
for col in speed_cols:
    df1[f'{col}_kmh'] = df1[col].apply(lambda x: simple_extract(x, 'km/h'))
    df1[f'{col}_kt'] = df1[col].apply(lambda x: simple_extract(x, 'kt'))

In [99]:
if 'info_thrust' in df1.columns:
    df1['info_thrust_lbf'] = df1['info_thrust'].apply(lambda x: simple_extract(x, 'lbf'))
    df1['info_thrust_kn'] = df1['info_thrust'].apply(lambda x: simple_extract(x, 'kN'))

if 'info_power' in df1.columns:
    df1['info_power_shp'] = df1['info_power'].apply(lambda x: simple_extract(x, 'shp'))
    df1['info_power_kw'] = df1['info_power'].apply(lambda x: simple_extract(x, 'kW'))

if 'performance_fuel_burn' in df1.columns:
    df1['performance_fuel_burn_nm_gal'] = df1['performance_fuel_burn'].apply(lambda x: simple_extract(x, 'nm/gal'))
    df1['performance_fuel_burn_kml'] = df1['performance_fuel_burn'].apply(lambda x: simple_extract(x, 'km/L'))

if 'performance_rate_of_climb' in df1.columns:
    df1['performance_rate_of_climb_ft_min'] = df1['performance_rate_of_climb'].apply(lambda x: simple_extract(x, 'ft/min'))
    df1['performance_rate_of_climb_ms'] = df1['performance_rate_of_climb'].apply(lambda x: simple_extract(x, 'm/s'))

if 'size_baggage_volume' in df1.columns:
    df1['size_baggage_volume_ft3'] = df1['size_baggage_volume'].apply(lambda x: simple_extract(x, 'ft³'))
    df1['size_baggage_volume_m3'] = df1['size_baggage_volume'].apply(lambda x: simple_extract(x, 'm³'))

if 'weight_fuel_capacity' in df1.columns:
    df1['weight_fuel_capacity_gal'] = df1['weight_fuel_capacity'].apply(lambda x: simple_extract(x, 'gal'))
    df1['weight_fuel_capacity_l'] = df1['weight_fuel_capacity'].apply(lambda x: simple_extract(x, 'L'))
    df1['weight_fuel_capacity_kg'] = df1['weight_fuel_capacity'].apply(lambda x: simple_extract(x, 'kg'))

In [101]:
size_columns = [
    'size_cabin_height', 'size_cabin_length', 'size_cabin_width',
    'size_exterior_length', 'size_fuselage_diameter', 
    'size_tail_height', 'size_wing_span'
]
for col in size_columns:
    if col in df1.columns:
        df1[f'{col}_m'] = df1[col].apply(lambda x: simple_extract(x, 'm'))
        df1[f'{col}_ft'] = df1[col].apply(lambda x: simple_extract(x, 'ft'))

In [102]:
# Ümumi sərnişin tutumu (xanadakı ən böyük rəqəm)
df1['info_seats_total'] = df1['info_seats'].apply(lambda x: simple_extract(x, 'SUM'))

# Kateqoriyalara görə ayırma
df1['info_seats_economy'] = df1['info_seats'].apply(lambda x: simple_extract(x, 'Economy'))
df1['info_seats_business'] = df1['info_seats'].apply(lambda x: simple_extract(x, 'Business'))
df1['info_seats_first'] = df1['info_seats'].apply(lambda x: simple_extract(x, 'First'))

In [103]:
df1.head()

,name,url,info_avionics,info_crew,info_engine,info_engine_type,info_power,info_seats,info_thrust,info_wing_tips,performance_approach_speed,performance_ceiling,performance_cruise_speed,performance_fuel_burn,performance_landing_distance,performance_max_cruise_speed,performance_maximum_speed,performance_range,performance_rate_of_climb,performance_takeoff_distance,size_baggage_volume,size_cabin_height,size_cabin_length,size_cabin_width,size_exterior_length,size_fuselage_diameter,size_tail_height,size_wing_span,weight_empty_weight,weight_fuel_capacity,weight_gross_weight,weight_max_landing_weight,weight_max_payload,weight_max_takeoff_weight,weight_gross_weight_kg,weight_gross_weight_lb,weight_max_takeoff_weight_kg,weight_max_takeoff_weight_lb,weight_max_landing_weight_kg,weight_max_landing_weight_lb,weight_max_payload_kg,weight_max_payload_lb,performance_range_m,performance_range_mi,performance_range_km,performance_range_nm,performance_range_ft,performance_landing_distance_m,performance_landing_distance_mi,performance_landing_distance_km,performance_landing_distance_nm,performance_landing_distance_ft,performance_takeoff_distance_m,performance_takeoff_distance_mi,performance_takeoff_distance_km,performance_takeoff_distance_nm,performance_takeoff_distance_ft,performance_ceiling_m,performance_ceiling_mi,performance_ceiling_km,performance_ceiling_nm,performance_ceiling_ft,performance_approach_speed_kmh,performance_approach_speed_kt,performance_cruise_speed_kmh,performance_cruise_speed_kt,performance_max_cruise_speed_kmh,performance_max_cruise_speed_kt,performance_maximum_speed_kmh,performance_maximum_speed_kt,info_thrust_lbf,info_thrust_kn,info_power_shp,info_power_kw,performance_fuel_burn_nm_gal,performance_fuel_burn_kml,performance_rate_of_climb_ft_min,performance_rate_of_climb_ms,size_baggage_volume_ft3,size_baggage_volume_m3,weight_fuel_capacity_gal,weight_fuel_capacity_l,weight_fuel_capacity_kg,size_cabin_height_m,size_cabin_height_ft,size_cabin_length_m,size_cabin_length_ft,size_cabin_width_m,size_cabin_width_ft,size_exterior_length_m,size_exterior_length_ft,size_fuselage_diameter_m,size_fuselage_diameter_ft,size_tail_height_m,size_tail_height_ft,size_wing_span_m,size_wing_span_ft,info_seats_total,info_seats_economy,info_seats_business,info_seats_first
0,Airbus A300,https://aerocorner.com/aircraft/airbus-a300-600/,Honeywell 331-250,NaN,2 × Pratt & Whitney PW4000,Turbofan,NaN,NaN,"2 × 99,040 lbf · 441 kN",Wingtip fences,131 kt · 151 mph · 243 km/h,"40,000 ft · 12,200 m",NaN,NaN,"5,050 ft · 1,540 m",484 kt · 557 mph · 896 km/h,NaN,"4,050 nm · 4,660 mi · 7,500 km","3,000 ft/min · 15 m/s","7,800 ft · 2,380 m",NaN,NaN,133 ft 6 in · 40.70 m,17 ft 4 in · 5.28 m,177 ft 6 in · 54.10 m,18 ft 6 in · 5.64 m,NaN,147 ft 1 in · 44.84 m,NaN,"18,000gal·68,100L·54,500kg(Jet A)",NaN,"304,000 lb · 138,000 kg","120,500 lb · 55,000 kg","364,000 lb · 165,000 kg",None,None,165000.0,364000.0,138000.0,304000.0,55000.0,120500.0,4660.0,4660.0,7500.0,4050.0,None,1540.0,None,None,None,5050.0,2380.0,None,None,None,7800.0,12200.0,None,None,None,40000.0,243.0,131.0,None,None,896.0,484.0,None,None,99040.0,441.0,NaN,NaN,NaN,NaN,3000.0,15.0,NaN,NaN,18000.0,68100.0,54500.0,NaN,NaN,40.70,133.0,5.28,17.0,54.10,177.0,5.64,18.0,NaN,NaN,44.84,147.0,NaN,NaN,NaN,NaN
1,Airbus A310,https://aerocorner.com/aircraft/airbus-a310-300/,Honeywell 331-250,NaN,2 × JT9D-7R4E1 / PW4000 / CF6-80C2,Turbofan,NaN,243,"2 × 62,000 lbf · 276 kN",No winglets,139 kt · 160 mph · 257 km/h,"41,000 ft · 12,500 m",NaN,NaN,"4,900 ft · 1,490 m",482 kt · 555 mph · 893 km/h,NaN,"5,150 nm · 5,930 mi · 9,540 km","2,500 ft/min · 13 m/s","7,500 ft · 2,290 m","3,962 ft³ · 112.2 m³",7 ft 8 in · 2.33 m,109 ft 1 in · 33.24 m,17 ft 4 in · 5.28 m,153 ft 1 in · 46.66 m,18 ft 4 in · 5.60 m,52 ft 1 in · 15.87 m,144 ft 0 in · 43.90 m,NaN,"16,150gal·61,100L·48,900kg(Jet A)",NaN,"273,500 lb · 124,000 kg","76,500 lb · 34,800 kg","361,500 lb · 164,000 kg",None,None,164000.0,361500.0,124000.0,273500.0,34800.0,76500.0,5930.0,5930.0,9540.0,5150.0,None,1490.0,None,None,None,4900.0,2290.0,None,None,None,7500.0,12500.0,None,None,None,41000.0,257.0,139.0,None,None,893.0,482.0,None,None,62000.0,276.0,NaN,NaN,NaN,NaN,2500.0,13.0,3962.0,112.2,16150.0,61100.0,48900.0,2.33,7.0,33.24,109.0,5.28,17.0,46.66,153.0,5.60,18.0,15.87,52.0,43.90,144.0,243.0,NaN,NaN,NaN
2,Airbus A319,https://aerocorner.com/aircraft/airbus-industr...,Thales D-HUDS Avionics,NaN,2 × International Aero Engines V2500,Turbofan,NaN,156 economy·124 business,"2 × 23,500 lbf · 105 kN",Wingtip fences,NaN,"41,000 ft · 12,500 m",NaN,0.54 nm/gal · 0.26 km/L,"4,750 ft · 1,450 m",514 kt · 592 mph · 952 km/h,NaN,"3,672 nm · 4,230 mi · 6,800 km","3,500 ft/min · 18 m/s","6,400 ft · 1,950 m",976 ft³ · 27.6 m³,7 ft 3 in · 2.22 m,78 ft 0 in · 23.78 m,12 ft 2 in · 3.70 m,111 ft 0 in · 33.84 m,13 ft 0 in · 3.96 m,38 ft 7 in · 11.76 m,111 ft 11 in · 34.10 m,NaN,"6,300gal·23,900L·19,100kg(Jet A)",NaN,"138,000 lb · 62,500 kg","30,900 lb · 14,000 kg","166,500 lb · 75,500 kg",None,None,75500.0,166500.0,62500.0,138000.0,14000.0,30900.0,4230.0,4230.0,6800.0,3672.0,None,1450.0,None,None,None,4750.0,1950.0,None,None,None,6400.0,12500.0,None,None,None,41000.0,NaN,NaN,None,None,952.0,514.0,None,None,23500.0,105.0,NaN,NaN,0.54,0.26,3500.0,18.0,976.0,27.6,6300.0,23900.0,19100.0,2.22,7.0,23.78,78.0,3.70,12.0,33.84,111.0,3.96,13.0,11.76,38.0,34.10,111.0,280.0,156.0,124.0,NaN
3,Airbus A320,https://aerocorner.com/aircraft/airbus-a320/,Thales Avionics Suite,NaN,2 × IAE V2500 or CFM International CFM56-5B,Turbofan,NaN,190 economy·148 business,"2 × 27,000 lbf · 120 kN",Wingtip fences,137 kt · 158 mph · 254 km/h,"39,000 ft · 11,900 m",NaN,0.45 nm/gal · 0.22 km/L,"5,050 ft · 1,540 m",514 kt · 592 mph · 952 km/h,NaN,"3,300 nm · 3,800 mi · 6,110 km","2,500 ft/min · 13 m/s","6,900 ft · 2,100 m","1,321 ft³ · 37.4 m³",7 ft 3 in · 2.22 m,90 ft 3 in · 27.50 m,12 ft 2 in · 3.70 m,123 ft 3 in · 37.57 m,13 ft 0 in · 3.95 m,39 ft 8 in · 12.08 m,117 ft 5 in · 35.80 m,NaN,"7,850gal·29,700L·23,700kg(Jet A)",NaN,"145,500 lb · 66,000 kg","44,000 lb · 20,000 kg","172,000 lb · 78,000 kg",None,None,78000.0,172000.0,66000.0,145500.0,20000.0,44000.0,3800.0,3800.0,6110.0,3300.0,None,1540.0,None,None,None,5050.0,2100.0,None,None,None,6900.0,11900.0,None,None,None,39000.0,254.0,137.0,None,None,952.0,514.0,None,None,27000.0,120.0,NaN,NaN,0.45,0.22,2500.0,13.0,1321.0,37.4,7850.0,29700.0,23700.0,2.22,7.0,27.50,90.0,3.70,12.0,37.57,123.0,3.95,13.0,12.08,39.0,35.80,117.0,338.0,190.0,148.0,NaN
4,Airbus A321,https://aerocorner.com/aircraft/airbus-industr...,Thales Avionics Suite,NaN,NaN,-,NaN,220 economy·185 business,"56,200 lbf · 250 kN",No winglets,NaN,"39,000 ft · 11,900 m",NaN,0.45 nm/gal · 0.22 km/L,"5,050 ft · 1,540 m","542 kt · 624 mph · 1,004 km/h",NaN,"3,200 nm · 3,680 mi · 5,930 km",12 ft/min · 0 m/s,"5,600 ft · 1,710 m","1,828 ft³ · 51.8 m³",7 ft 3 in · 2.22 m,113 ft 0 in · 34.44 m,12 ft 2 in · 3.70 m,146 ft 0 in · 44.51 m,13 ft 0 in · 3.96 m,NaN,111 ft 11 in · 34.10 m,NaN,"7,850gal·29,700L·23,700kg(Jet A)",NaN,NaN,"47,900 lb · 21,700 kg","206,000 lb · 93,500 kg",None,None,93500.0,206000.0,NaN,NaN,21700.0,47900.0,3680.0,3680.0,5930.0,3200.0,None,1540.0,None,None,None,5050.0,1710.0,None,None,None,5600.0,11900.0,None,None,None,39000.0,NaN,NaN,None,None,1004.0,542.0,None,None,56200.0,250.0,NaN,NaN,0.45,0.22,12.0,0.0,1828.0,51.8,7850.0,29700.0,23700.0,2.22,7.0,34.44,113.0,3.70,12.0,44.51,146.0,3.96,13.0,NaN,NaN,34.10,111.0,405.0,220.0,185.0,NaN

In [104]:
# 1. Parçaladığım orijinal sütunların siyahısı
original_cols_to_drop = [
    'info_seats', 'info_thrust', 'info_power', 'performance_range', 'size_fuselage_diameter', 'size_tail_height', 'size_wing_span',
    'performance_landing_distance', 'performance_takeoff_distance', 'performance_approach_speed', 'performance_max_cruise_speed',
    'performance_ceiling', 'performance_rate_of_climb', 'size_cabin_height', 'size_cabin_length', 'size_cabin_width', 'size_exterior_length',
    'performance_fuel_burn', 'size_baggage_volume', 'weight_fuel_capacity', 'weight_max_landing_weight', 'weight_max_payload', 
    'weight_max_takeoff_weight', 'performance_range_m'
]

df1.drop(columns=[col for col in original_cols_to_drop if col in df1.columns], inplace=True)

# 2. Tamamilə boş sütunların silinməsi
df1.dropna(axis=1, how='all', inplace=True)

In [105]:
df1.columns

Index(['name', 'url', 'info_avionics', 'info_engine', 'info_engine_type',
       'info_wing_tips', 'weight_max_takeoff_weight_kg',
       'weight_max_takeoff_weight_lb', 'weight_max_landing_weight_kg',
       'weight_max_landing_weight_lb', 'weight_max_payload_kg',
       'weight_max_payload_lb', 'performance_range_mi', 'performance_range_km',
       'performance_range_nm', 'performance_landing_distance_m',
       'performance_landing_distance_ft', 'performance_takeoff_distance_m',
       'performance_takeoff_distance_ft', 'performance_ceiling_m',
       'performance_ceiling_ft', 'performance_approach_speed_kmh',
       'performance_approach_speed_kt', 'performance_max_cruise_speed_kmh',
       'performance_max_cruise_speed_kt', 'info_thrust_lbf', 'info_thrust_kn',
       'info_power_shp', 'info_power_kw', 'performance_fuel_burn_nm_gal',
       'performance_fuel_burn_kml', 'performance_rate_of_climb_ft_min',
       'performance_rate_of_climb_ms', 'size_baggage_volume_ft3',
       'size_baggage_volume_m3', 'weight_fuel_capacity_gal',
       'weight_fuel_capacity_l', 'weight_fuel_capacity_kg',
       'size_cabin_height_m', 'size_cabin_height_ft', 'size_cabin_length_m',
       'size_cabin_length_ft', 'size_cabin_width_m', 'size_cabin_width_ft',
       'size_exterior_length_m', 'size_exterior_length_ft',
       'size_fuselage_diameter_m', 'size_fuselage_diameter_ft',
       'size_tail_height_m', 'size_tail_height_ft', 'size_wing_span_m',
       'size_wing_span_ft', 'info_seats_total', 'info_seats_economy',
       'info_seats_business', 'info_seats_first'],
      dtype='object')

In [106]:
# 1. df_basic: Əsas Məlumatlar və Oturacaqlar
basic_cols = [
    'name', 'url', 'info_avionics', 'info_engine', 'info_engine_type', 
    'info_wing_tips', 'info_seats_total', 'info_seats_economy', 
    'info_seats_business', 'info_seats_first'
]

# 2. df_range_altitude: Məsafə və Hündürlük
range_alt_cols = [
    'name', 'performance_range_km', 'performance_range_nm', 'performance_range_mi', 
    'performance_landing_distance_m', 'performance_landing_distance_ft', 
    'performance_takeoff_distance_m', 'performance_takeoff_distance_ft', 
    'performance_ceiling_m', 'performance_ceiling_ft'
]

# 3. df_speed: Sürətlər
speed_cols = [
    'name', 'performance_approach_speed_kmh', 'performance_approach_speed_kt', 
    'performance_max_cruise_speed_kmh', 'performance_max_cruise_speed_kt'
]

# 4. df_engine_metrics: Mühərrik Gücü və Effektivlik
engine_perf_cols = [
    'name', 'info_thrust_lbf', 'info_thrust_kn', 'info_power_shp', 'info_power_kw', 
    'performance_fuel_burn_nm_gal', 'performance_fuel_burn_kml', 
    'performance_rate_of_climb_ft_min', 'performance_rate_of_climb_ms'
]

# 5. df_weights: Çəki və Yanacaq Tutumu (Tam siyahı)
weight_cols = [
    'name', 'weight_max_takeoff_weight_kg', 'weight_max_takeoff_weight_lb', 
    'weight_max_landing_weight_kg', 'weight_max_landing_weight_lb', 'weight_max_payload_kg', 
    'weight_max_payload_lb', 'weight_fuel_capacity_gal', 'weight_fuel_capacity_l', 'weight_fuel_capacity_kg'
]

# 6. df_dimensions: Fiziki Ölçülər (Tam siyahı)
dim_cols = [
    'name', 'size_baggage_volume_ft3', 'size_baggage_volume_m3', 'size_cabin_height_m', 
    'size_cabin_height_ft', 'size_cabin_length_m', 'size_cabin_length_ft', 'size_cabin_width_m', 
    'size_cabin_width_ft', 'size_exterior_length_m', 'size_exterior_length_ft', 'size_fuselage_diameter_m', 
    'size_fuselage_diameter_ft', 'size_tail_height_m', 'size_tail_height_ft', 'size_wing_span_m', 'size_wing_span_ft'
]

df_basic_specs = df1[[c for c in basic_cols if c in df1.columns]].copy()
df_range_altitude_specs = df1[[c for c in range_alt_cols if c in df1.columns]].copy()
df_speed_specs = df1[[c for c in speed_cols if c in df1.columns]].copy()
df_engine_metrics_specs = df1[[c for c in engine_perf_cols if c in df1.columns]].copy()
df_weights_specs = df1[[c for c in weight_cols if c in df1.columns]].copy()
df_dimensions_specs = df1[[c for c in dim_cols if c in df1.columns]].copy()

In [107]:
df_basic_specs.to_csv('1_aircraft_basic.csv', index=False, encoding='utf-8-sig')
df_range_altitude_specs.to_csv('2_aircraft_range_alt.csv', index=False, encoding='utf-8-sig')
df_speed_specs.to_csv('3_aircraft_speed.csv', index=False, encoding='utf-8-sig')
df_engine_metrics_specs.to_csv('4_aircraft_engine_metrics.csv', index=False, encoding='utf-8-sig')
df_weights_specs.to_csv('5_aircraft_weights.csv', index=False, encoding='utf-8-sig')
df_dimensions_specs.to_csv('6_aircraft_dimensions.csv', index=False, encoding='utf-8-sig')

In [111]:
df2 = pd.read_csv("airline_fundamentals.csv")

In [114]:
df2

,airline_name,ticker,currency,exchange,market_cap,enterprise_value,trailing_pe,forward_pe,price_to_book,profit_margins,operating_margins,return_on_assets,return_on_equity,debt_to_equity,total_cash,total_debt,revenue_ttm,ebitda_ttm
0,Delta Air Lines,DAL,USD,NYQ,4.521624e+10,6.203425e+10,9.037860,8.308002,2.156698,0.07899,0.08930,0.04502,0.27693,102.498,4.310000e+09,2.137400e+10,6.336400e+10,7.772000e+09
1,Air Canada,AC.TO,CAD,TOR,5.983298e+09,1.200090e+10,10.860215,8.169439,2.296499,0.02879,0.03033,0.01886,0.25869,446.777,5.525000e+09,1.157600e+10,2.237200e+10,2.238000e+09
2,Lufthansa,LHA.DE,EUR,GER,1.090207e+10,1.612700e+10,6.689705,7.047250,0.959806,0.04176,0.07626,0.01895,0.15246,126.944,9.381000e+09,1.449700e+10,3.934700e+10,3.393000e+09
3,Turkish Airlines,THYAO.IS,TRY,IST,4.235972e+11,4.349636e+11,3.548406,4.280061,20.879904,0.11695,0.14799,0.02896,0.14207,76.091,6.250000e+09,1.550200e+10,2.342900e+10,2.850000e+09
4,Finnair,FIA1S.HE,EUR,HEL,7.225011e+08,1.451216e+09,39.200000,7.474577,1.134770,0.00592,0.04940,0.00842,0.02912,285.378,1.093200e+09,1.817000e+09,3.106200e+09,2.591000e+08
5,Air France,AF.PA,EUR,PAR,3.385665e+09,1.620423e+10,3.966154,2.472717,-3.443762,0.04826,0.05827,0.03442,1.10907,656.218,4.714000e+09,1.551300e+10,3.300700e+10,3.672000e+09
6,KLM Royal Dutch Airlines,AF.PA,EUR,PAR,3.385665e+09,1.620423e+10,3.966154,2.472717,-3.443762,0.04826,0.05827,0.03442,1.10907,656.218,4.714000e+09,1.551300e+10,3.300700e+10,3.672000e+09
7,British Airways,IAG.L,GBp,LSE,1.999983e+10,2.558974e+10,7.823214,6.620393,393.214970,0.09300,0.22256,NaN,NaN,248.481,9.348000e+09,1.480700e+10,3.328100e+10,6.277750e+09
8,Iberia,IAG.L,GBp,LSE,1.999983e+10,2.558974e+10,7.823214,6.620393,393.214970,0.09300,0.22256,NaN,NaN,248.481,9.348000e+09,1.480700e+10,3.328100e+10,6.277750e+09
9,Vueling,IAG.L,GBp,LSE,1.999983e+10,2.558974e+10,7.823214,6.620393,393.214970,0.09300,0.22256,NaN,NaN,248.481,9.348000e+09,1.480700e+10,3.328100e+10,6.277750e+09
10,Aegean Airlines,AEGN.AT,EUR,ATH,1.246648e+09,2.142794e+09,8.069365,8.268918,2.246540,0.07849,0.22809,0.04498,0.28396,292.466,7.329000e+08,1.630500e+09,1.859446e+09,2.779243e+08
11,Qantas Airways,QAN.AX,AUD,ASX,1.611557e+10,2.148220e+10,10.240385,8.325645,20.679611,0.06737,0.09005,0.06987,2.98050,1016.092,2.213000e+09,7.956000e+09,2.382300e+10,4.121000e+09
12,Air New Zealand,AIR.NZ,NZD,NZE,1.886114e+09,3.293439e+09,14.375000,15.548945,0.977891,0.01865,0.00298,0.01259,0.06370,145.838,1.436000e+09,2.838000e+09,6.755000e+09,5.510000e+08
13,ANA All Nippon Airways,9202.T,JPY,JPX,1.546341e+12,1.522014e+12,11.804088,11.924254,1.084536,0.06494,0.12094,0.03473,0.12322,81.908,1.229950e+12,1.188294e+12,2.436456e+12,3.699770e+11
14,Japan Airlines,9201.T,JPY,JPX,1.367298e+12,1.346972e+12,11.308464,12.750843,1.122905,0.06490,0.12669,0.04314,0.12172,68.373,9.150580e+11,8.666470e+11,1.998823e+12,3.636650e+11
15,Korean Air,003490.KS,KRW,KSC,1.069214e+13,2.519355e+13,NaN,8.283262,NaN,0.04081,0.02613,0.02209,0.08485,189.536,6.398715e+12,2.135977e+13,2.323122e+13,4.020558e+12
16,Singapore Airlines,C6L.SI,SGD,SES,2.240443e+10,2.473927e+10,10.098592,21.689808,1.442656,0.11535,0.08715,0.02706,0.15387,68.227,8.511300e+09,1.087480e+10,1.971760e+10,3.382500e+09
17,Cathay Pacific Airways,0293.HK,HKD,HKG,8.725399e+10,1.423795e+11,9.609929,10.834973,1.689105,0.09100,0.10912,0.04768,0.17557,126.312,8.912000e+09,6.525400e+10,1.090760e+11,2.086800e+10
18,China Southern Airlines,1055.HK,HKD,HKG,1.116249e+11,3.349885e+11,NaN,43.495890,2.662953,-0.00764,0.11809,0.01406,0.00829,399.837,1.952000e+10,2.262360e+11,1.772280e+11,1.878900e+10
19,AirAsia,5099.KL,MYR,KLS,2.700424e+09,2.348435e+09,NaN,13.355409,-0.489086,0.67289,-0.35402,-0.01320,NaN,NaN,3.846240e+08,1.493650e+09,1.834063e+09,-5.916550e+08
20,IndiGo,INDIGO.NS,INR,NSI,1.911839e+12,2.127165e+12,59.622620,24.165121,22.139200,0.03793,0.15758,NaN,NaN,866.462,4.962910e+11,7.481380e+11,8.467540e+11,1.137992e+11
21,China Airlines,2610.TW,TWD,TAI,1.283270e+11,1.857945e+11,8.683127,10.052980,1.360851,0.07217,0.08446,0.03972,0.17684,102.419,4.989732e+10,1.014204e+11,2.079275e+11,3.699293e+10
22,EVA Air,2618.TW,TWD,TAI,2.049469e+11,2.518089e+11,7.955975,9.169524,1.556285,0.11868,0.15137,0.06674,0.20583,79.777,7.403849e+10,1.119693e+11,2.192463e+11,5.089149e+10
23,STARLUX Airlines,2646.TW,TWD,TAI,6.950178e+10,1.369190e+11,462.000000,NaN,2.149437,0.00623,-0.00594,0.00816,0.01004,256.481,1.460915e+10,8.292900e+10,4.231646e+10,4.548796e+09
24,LATAM Airlines,LTM.SN,CLP,SGO,1.433817e+13,1.434410e+13,11.613953,26.284210,12484.999000,0.10235,0.16944,0.08875,1.42889,604.884,2.150113e+09,8.088526e+09,1.426506e+10,3.556321e+09
25,Garuda Indonesia,GIAA.JK,IDR,JKT,7.684386e+12,7.779838e+12,2.281989,NaN,-5249.999500,-0.03822,0.02628,0.02133,NaN,NaN,2.431368e+08,4.244745e+09,3.244864e+09,3.726767e+08
26,Air Astana,AIRA.IL,USD,IOB,NaN,NaN,NaN,20.424240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [115]:
# 1. df_airline_identity: Şirkət və birja məlumatları
identity_cols = ['airline_name', 'ticker', 'currency', 'exchange']
df_airline_identity = df2[identity_cols].copy()

# 2. df_airline_market: Bazar dəyəri və P/E göstəriciləri
market_cols = [
    'airline_name', 'market_cap', 'enterprise_value', 
    'trailing_pe', 'forward_pe', 'price_to_book']
df_airline_market = df2[market_cols].copy()

# 3. df_airline_finance: Maliyyə həcmləri və rentabellik nisbətləri
finance_cols = [
    'airline_name', 'profit_margins', 'operating_margins', 'return_on_assets', 
    'return_on_equity', 'debt_to_equity', 'total_cash', 'total_debt', 
    'revenue_ttm', 'ebitda_ttm']
df_airline_finance = df2[finance_cols].copy()

In [116]:
df_airline_identity.to_csv('airline_identity.csv', index=False, encoding='utf-8-sig')
df_airline_market.to_csv('airline_market.csv', index=False, encoding='utf-8-sig')
df_airline_finance.to_csv('airline_finance.csv', index=False, encoding='utf-8-sig')

In [123]:
df3 = pd.read_csv("airline_income_statement_metrics.csv")

In [124]:
df3

        airline_name   ticker  period_end             metric         value
0    Delta Air Lines      DAL  2025-12-31      total_revenue  6.336400e+10
1    Delta Air Lines      DAL  2024-12-31      total_revenue  6.164300e+10
2    Delta Air Lines      DAL  2023-12-31      total_revenue  5.804800e+10
3    Delta Air Lines      DAL  2022-12-31      total_revenue  5.058200e+10
4    Delta Air Lines      DAL  2021-12-31      total_revenue           NaN
..               ...      ...         ...                ...           ...
691       Air Astana  AIRA.IL  2021-12-31    cost_of_revenue  5.947310e+08
692       Air Astana  AIRA.IL  2024-12-31  operating_expense  1.112950e+08
693       Air Astana  AIRA.IL  2023-12-31  operating_expense  1.004270e+08
694       Air Astana  AIRA.IL  2022-12-31  operating_expense  8.293400e+07
695       Air Astana  AIRA.IL  2021-12-31  operating_expense  6.482100e+07

[696 rows x 5 columns]

In [125]:
df3["metric"].unique()

array(['total_revenue', 'operating_income', 'net_income', 'ebitda',
       'cost_of_revenue', 'operating_expense'], dtype=object)

In [126]:
df3 = df3.pivot_table(
    index=['airline_name', 'ticker', 'period_end'], 
    columns='metric', 
    values='value'
).reset_index()

In [127]:
df3

metric,airline_name,ticker,period_end,cost_of_revenue,ebitda,net_income,operating_expense,operating_income,total_revenue
0,ANA All Nippon Airways,9202.T,2022-03-31,1.049414e+12,9.590000e+09,-1.436280e+11,1.440370e+11,-1.731270e+11,1.020324e+12
1,ANA All Nippon Airways,9202.T,2023-03-31,1.403567e+12,2.895720e+11,8.947700e+10,1.838870e+11,1.200300e+11,1.707484e+12
2,ANA All Nippon Airways,9202.T,2024-03-31,1.642263e+12,3.725930e+11,1.570970e+11,2.057540e+11,2.079110e+11,2.055928e+12
3,ANA All Nippon Airways,9202.T,2025-03-31,1.843542e+12,3.705850e+11,1.530270e+11,2.216750e+11,1.966390e+11,2.261856e+12
4,Aegean Airlines,AEGN.AT,2021-12-31,7.497855e+08,1.712654e+08,4.905160e+06,-1.836664e+08,3.005592e+07,5.961751e+08
...,...,...,...,...,...,...,...,...,...
103,Turkish Airlines,THYAO.IS,2024-12-31,1.834700e+10,6.503000e+09,3.425000e+09,1.862000e+09,2.460000e+09,2.266900e+10
104,Vueling,IAG.L,2021-12-31,9.480000e+09,-8.230000e+08,-2.933000e+09,1.754000e+09,-2.779000e+09,8.455000e+09
105,Vueling,IAG.L,2022-12-31,1.896900e+10,3.501000e+09,4.310000e+08,2.700000e+09,1.397000e+09,2.306600e+10
106,Vueling,IAG.L,2023-12-31,2.275600e+10,6.214000e+09,2.655000e+09,3.166000e+09,3.531000e+09,2.945300e+10
107,Vueling,IAG.L,2024-12-31,2.452100e+10,6.829000e+09,2.732000e+09,3.278000e+09,4.301000e+09,3.210000e+10

In [128]:
df3.to_csv('airline_income_metric_new.csv', index=False, encoding='utf-8-sig')

In [129]:
df4 = pd.read_csv("airlines_metadata.csv")

In [130]:
df4

,airline_id,name,iata,icao,callsign,country,active
0,-1,Unknown,-,NaN,\N,\N,Y
1,1,Private flight,-,NaN,NaN,NaN,Y
2,2,135 Airways,NaN,GNL,GENERAL,United States,N
3,3,1Time Airline,1T,RNX,NEXTIME,South Africa,Y
4,4,2 Sqn No 1 Elementary Flying Training School,NaN,WYT,NaN,United Kingdom,N
...,...,...,...,...,...,...,...
6157,21248,GX Airlines,NaN,CBG,SPRAY,China,Y
6158,21251,Lynx Aviation (L3/SSX),NaN,SSX,Shasta,United States,N
6159,21268,Jetgo Australia,JG,\N,NaN,Australia,Y
6160,21270,Air Carnival,2S,\N,NaN,India,Y
6161,21317,Svyaz Rossiya,7R,SJM,RussianConnecty,Russia,Y

In [131]:
# Texniki işarələri (\N, -, boş) NaN ilə əvəz edirik
df4.replace(['\\N', '-', ''], np.nan, inplace=True)

# 'active' sütununu standartlaşdırırıq (hamısı böyük hərf)
df4['active'] = df4['active'].str.upper()

# Naməlum olan ilk sətri silirik (əgər id -1-dirsə)
df4 = df4[df4['airline_id'] != -1]

In [132]:
df4

,airline_id,name,iata,icao,callsign,country,active
1,1,Private flight,NaN,NaN,NaN,NaN,Y
2,2,135 Airways,NaN,GNL,GENERAL,United States,N
3,3,1Time Airline,1T,RNX,NEXTIME,South Africa,Y
4,4,2 Sqn No 1 Elementary Flying Training School,NaN,WYT,NaN,United Kingdom,N
5,5,213 Flight Unit,NaN,TFU,NaN,Russia,N
...,...,...,...,...,...,...,...
6157,21248,GX Airlines,NaN,CBG,SPRAY,China,Y
6158,21251,Lynx Aviation (L3/SSX),NaN,SSX,Shasta,United States,N
6159,21268,Jetgo Australia,JG,NaN,NaN,Australia,Y
6160,21270,Air Carnival,2S,NaN,NaN,India,Y
6161,21317,Svyaz Rossiya,7R,SJM,RussianConnecty,Russia,Y

In [133]:
df4.to_csv('airlines_metadata_cleaned.csv', index=False, encoding='utf-8-sig')

In [134]:
df5 = pd.read_csv("airlines_stock_data.csv")

In [135]:
df5

,date,airline_name,ticker,adj_close,close,high,low,open,volume,daily_return,rolling_volatility_30d
0,2015-01-02,Singapore Airlines,C6L.SI,5.687865,8.137768,8.165951,8.116631,8.158905,759329,0.346323,1.578161
1,2015-01-05,Singapore Airlines,C6L.SI,5.707563,8.165951,8.180042,8.109585,8.130722,2363147,0.346323,1.578161
2,2015-01-06,Singapore Airlines,C6L.SI,5.751883,8.229362,8.229362,8.158905,8.187088,3570978,0.776526,1.578161
3,2015-01-07,Singapore Airlines,C6L.SI,5.889772,8.426641,8.426641,8.215271,8.229362,6361338,2.397269,1.578161
4,2015-01-08,Singapore Airlines,C6L.SI,5.919320,8.468915,8.468915,8.384367,8.440733,3961288,0.501665,1.578161
...,...,...,...,...,...,...,...,...,...,...,...
69844,2026-02-13,Gulfstream (General Dynamics),GD,347.640015,347.640015,349.440002,341.660004,341.970001,1533600,2.022015,1.832061
69845,2026-02-17,Gulfstream (General Dynamics),GD,342.519989,342.519989,350.000000,340.089996,346.970001,1699800,-1.472795,1.818988
69846,2026-02-18,Gulfstream (General Dynamics),GD,349.489990,349.489990,349.549988,343.679993,344.859985,1232200,2.034918,1.737036
69847,2026-02-19,Gulfstream (General Dynamics),GD,354.339996,354.339996,356.390015,348.119995,348.119995,918400,1.387738,1.735275
69848,2026-02-20,Gulfstream (General Dynamics),GD,351.420013,351.420013,354.649994,348.690002,354.209991,893900,-0.824062,1.558886

In [138]:
df5.dtypes

date                      datetime64[ns]
airline_name                      object
ticker                            object
adj_close                        float64
close                            float64
high                             float64
low                              float64
open                             float64
volume                             int64
daily_return                     float64
rolling_volatility_30d           float64
dtype: object

In [137]:
#  Tarix sütununu real formatına çeviririk
df5['date'] = pd.to_datetime(df5['date'])

# df_stock_prices: Əsas birja qiymətləri
prices_cols = ['date', 'ticker', 'open', 'high', 'low', 'close', 'volume']
df_stock_prices = df5[prices_cols].copy()

# df_stock_analysis: Analitik və düzəliş edilmiş qiymətlər
analysis_cols = ['date', 'ticker', 'adj_close', 'daily_return', 'rolling_volatility_30d']
df_stock_analysis = df5[analysis_cols].copy()

In [139]:
df_stock_prices.to_csv('airline_stock_prices.csv', index=False, encoding='utf-8-sig')
df_stock_analysis.to_csv('airline_stock_analysis.csv', index=False, encoding='utf-8-sig')

In [140]:
df6 = pd.read_csv("oil_prices_data.csv")

In [141]:
df6

,date,commodity_name,ticker,adj_close,close,high,low,open,volume,daily_return,rolling_volatility_30d
0,2015-01-02,Brent Crude,BZ=F,56.419998,56.419998,58.220001,55.520000,57.630001,16707,-5.866710,3.012697
1,2015-01-05,Brent Crude,BZ=F,53.110001,53.110001,56.290001,52.669998,56.290001,30065,-5.866710,3.012697
2,2015-01-06,Brent Crude,BZ=F,51.099998,51.099998,53.520000,50.529999,53.230000,35494,-3.784602,3.012697
3,2015-01-07,Brent Crude,BZ=F,51.150002,51.150002,51.840000,49.680000,51.060001,37082,0.097853,3.012697
4,2015-01-08,Brent Crude,BZ=F,50.959999,50.959999,51.889999,49.820000,51.000000,29469,-0.371461,3.012697
...,...,...,...,...,...,...,...,...,...,...,...
5596,2026-02-13,WTI Crude,CL=F,62.889999,62.889999,63.259998,62.139999,62.990002,255793,0.079566,2.245677
5597,2026-02-17,WTI Crude,CL=F,62.330002,62.330002,64.139999,61.869999,63.299999,328727,-0.890440,2.254991
5598,2026-02-18,WTI Crude,CL=F,65.190002,65.190002,65.559998,62.119999,62.299999,115379,4.588482,2.374244
5599,2026-02-19,WTI Crude,CL=F,66.430000,66.430000,66.900002,64.879997,65.099998,113408,1.902129,2.343461
5600,2026-02-20,WTI Crude,CL=F,66.389999,66.389999,67.050003,65.940002,66.669998,113408,-0.060215,2.297717

In [143]:
df6.dtypes

date                      datetime64[ns]
commodity_name                    object
ticker                            object
adj_close                        float64
close                            float64
high                             float64
low                              float64
open                             float64
volume                             int64
daily_return                     float64
rolling_volatility_30d           float64
dtype: object

In [142]:
# Tarix sütununu düzəldirik
df6['date'] = pd.to_datetime(df6['date'])

# df_oil_prices: Neft qiymətləri
oil_prices_cols = ['date', 'commodity_name', 'ticker', 'open', 'high', 'low', 'close', 'volume']
df_oil_prices = df6[oil_prices_cols].copy()

# df_oil_analysis: Analitik göstəricilər
oil_analysis_cols = ['date', 'ticker', 'adj_close', 'daily_return', 'rolling_volatility_30d']
df_oil_analysis = df6[oil_analysis_cols].copy()

In [144]:
df_oil_prices.to_csv('oil_prices_main.csv', index=False, encoding='utf-8-sig')
df_oil_analysis.to_csv('oil_prices_analysis.csv', index=False, encoding='utf-8-sig')

In [145]:
df7 = pd.read_csv("planespotters_fleet_matrix.csv")

In [146]:
df7

,airline_name,aircraft_type,in_service,parked,total_current,future,historic,avg_age,total_all_time
0,Qatar Airways,Airbus A300,NaN,NaN,NaN,NaN,10.0,NaN,10
1,Qatar Airways,Airbus A310,NaN,NaN,NaN,NaN,2.0,NaN,2
2,Qatar Airways,Airbus A319,NaN,NaN,NaN,NaN,3.0,NaN,3
3,Qatar Airways,Airbus A320,27.0,NaN,27.0,NaN,18.0,13.6 Years,45
4,Qatar Airways,Airbus A321,6.0,NaN,6.0,NaN,12.0,0.4 Years,18
...,...,...,...,...,...,...,...,...,...
608,AZAL Azerbaijan Airlines,Boeing 777,1.0,NaN,1.0,NaN,NaN,6.2 Years,1
609,AZAL Azerbaijan Airlines,Boeing 787 Dreamliner,2.0,NaN,2.0,1.0,NaN,11.3 Years,3
610,AZAL Azerbaijan Airlines,Canadair CL-44,NaN,NaN,NaN,NaN,1.0,NaN,1
611,AZAL Azerbaijan Airlines,Embraer ERJ-170,NaN,NaN,NaN,NaN,1.0,NaN,1
612,AZAL Azerbaijan Airlines,Embraer ERJ-190,7.0,NaN,7.0,NaN,1.0,10.0 Years,8

In [147]:
# NaN dəyərləri 0 ilə əvəz edirik (Status sütunları üçün)
status_cols = ['in_service', 'parked', 'total_current', 'future', 'historic']
df7[status_cols] = df7[status_cols].fillna(0).astype(int)

In [148]:
# 'avg_age' sütununu təmizləyirik
def clean_age(text):
    if pd.isna(text) or text == '':
        return None
    # Rəqəmi və nöqtəni saxlayır, qalanını silir
    match = str(text).split()[0]
    try:
        return float(match)
    except ValueError:
        return None

df7['avg_age_numeric'] = df7['avg_age'].apply(clean_age)

In [149]:
# 5. Orijinal 'avg_age' sütununu silirik
df7.drop(columns=['avg_age'], inplace=True)

In [150]:
df7

,airline_name,aircraft_type,in_service,parked,total_current,future,historic,total_all_time,avg_age_numeric
0,Qatar Airways,Airbus A300,0,0,0,0,10,10,NaN
1,Qatar Airways,Airbus A310,0,0,0,0,2,2,NaN
2,Qatar Airways,Airbus A319,0,0,0,0,3,3,NaN
3,Qatar Airways,Airbus A320,27,0,27,0,18,45,13.6
4,Qatar Airways,Airbus A321,6,0,6,0,12,18,0.4
...,...,...,...,...,...,...,...,...,...
608,AZAL Azerbaijan Airlines,Boeing 777,1,0,1,0,0,1,6.2
609,AZAL Azerbaijan Airlines,Boeing 787 Dreamliner,2,0,2,1,0,3,11.3
610,AZAL Azerbaijan Airlines,Canadair CL-44,0,0,0,0,1,1,NaN
611,AZAL Azerbaijan Airlines,Embraer ERJ-170,0,0,0,0,1,1,NaN
612,AZAL Azerbaijan Airlines,Embraer ERJ-190,7,0,7,0,1,8,10.0

In [151]:
df7.to_csv('airline_fleet_cleaned.csv', index=False, encoding='utf-8-sig')

In [4]:
df11 = pd.read_csv(r"C:\Users\99455\OneDrive\Masaüstü\Data analitika və generativ süni intellekt\Python\scrape_tural\final_csv\new_file\aircraft_specs\1_aircraft_basic.csv")
df12 = pd.read_csv(r"C:\Users\99455\OneDrive\Masaüstü\Data analitika və generativ süni intellekt\Python\scrape_tural\final_csv\new_file\aircraft_specs\2_aircraft_range_alt.csv")
df13 = pd.read_csv(r"C:\Users\99455\OneDrive\Masaüstü\Data analitika və generativ süni intellekt\Python\scrape_tural\final_csv\new_file\aircraft_specs\3_aircraft_speed.csv")
df14 = pd.read_csv(r"C:\Users\99455\OneDrive\Masaüstü\Data analitika və generativ süni intellekt\Python\scrape_tural\final_csv\new_file\aircraft_specs\4_aircraft_engine_metrics.csv")
df15 = pd.read_csv(r"C:\Users\99455\OneDrive\Masaüstü\Data analitika və generativ süni intellekt\Python\scrape_tural\final_csv\new_file\aircraft_specs\5_aircraft_weights.csv")
df16 = pd.read_csv(r"C:\Users\99455\OneDrive\Masaüstü\Data analitika və generativ süni intellekt\Python\scrape_tural\final_csv\new_file\aircraft_specs\6_aircraft_dimensions.csv")

In [5]:
with pd.ExcelWriter('aircraft_specs.xlsx', engine='xlsxwriter') as writer:
    df11.to_excel(writer, sheet_name='1_aircraft_basic', index=False)
    df12.to_excel(writer, sheet_name='2_aircraft_range_alt', index=False)
    df13.to_excel(writer, sheet_name='3_aircraft_speed', index=False)
    df14.to_excel(writer, sheet_name='4_aircraft_engine_metrics', index=False)
    df15.to_excel(writer, sheet_name='5_aircraft_weights', index=False)
    df16.to_excel(writer, sheet_name='6_aircraft_dimensions', index=False)

In [5]:
df21 = pd.read_csv(r"C:\Users\99455\OneDrive\Masaüstü\Data analitika və generativ süni intellekt\Python\scrape_tural\final_csv\new_file\airline_fundamentals\airline_finance.csv")
df22 = pd.read_csv(r"C:\Users\99455\OneDrive\Masaüstü\Data analitika və generativ süni intellekt\Python\scrape_tural\final_csv\new_file\airline_fundamentals\airline_identity.csv")
df23 = pd.read_csv(r"C:\Users\99455\OneDrive\Masaüstü\Data analitika və generativ süni intellekt\Python\scrape_tural\final_csv\new_file\airline_fundamentals\airline_market.csv")

In [3]:
with pd.ExcelWriter('airline_fundamentals.xlsx', engine='xlsxwriter') as writer:
    df21.to_excel(writer, sheet_name='airline_finance', index=False)
    df22.to_excel(writer, sheet_name='airline_identity', index=False)
    df23.to_excel(writer, sheet_name='airline_market', index=False)

In [6]:
df31 = pd.read_csv(r"C:\Users\99455\OneDrive\Masaüstü\Data analitika və generativ süni intellekt\Python\scrape_tural\final_csv\new_file\airline_stock_data\airline_stock_analysis.csv")
df32 = pd.read_csv(r"C:\Users\99455\OneDrive\Masaüstü\Data analitika və generativ süni intellekt\Python\scrape_tural\final_csv\new_file\airline_stock_data\airline_stock_prices.csv")

In [4]:
with pd.ExcelWriter('airlines_stock_data.xlsx', engine='xlsxwriter') as writer:
    df31.to_excel(writer, sheet_name='airline_stock_analysis', index=False)
    df32.to_excel(writer, sheet_name='airline_stock_prices', index=False)

In [7]:
df41 = pd.read_csv(r"C:\Users\99455\OneDrive\Masaüstü\Data analitika və generativ süni intellekt\Python\scrape_tural\final_csv\new_file\oil_prices_data\oil_prices_analysis.csv")
df42 = pd.read_csv(r"C:\Users\99455\OneDrive\Masaüstü\Data analitika və generativ süni intellekt\Python\scrape_tural\final_csv\new_file\oil_prices_data\oil_prices_main.csv")

In [3]:
with pd.ExcelWriter('oil_prices_data.xlsx', engine='xlsxwriter') as writer:
    df41.to_excel(writer, sheet_name='oil_prices_analysis', index=False)
    df42.to_excel(writer, sheet_name='oil_prices_main', index=False)

In [8]:
df50 = pd.read_csv("airline_fleet_cleaned.csv")

In [9]:
df60 = pd.read_csv("airline_income_metric_new.csv")

In [10]:
df70 = pd.read_csv("airlines_metadata_cleaned.csv")

In [5]:
df50.to_excel("airline_fleet_cleaned.xlsx")
df60.to_excel("airline_income_metric_new.xlsx")
df70.to_excel("airlines_metadata_cleaned.xlsx")

In [25]:
with pd.ExcelWriter('FINAL_DATA.xlsx', engine='xlsxwriter') as writer:
    df11.to_excel(writer, sheet_name='1_aircraft_basic', index=False)
    df12.to_excel(writer, sheet_name='2_aircraft_range_alt', index=False)
    df13.to_excel(writer, sheet_name='3_aircraft_speed', index=False)
    df14.to_excel(writer, sheet_name='4_aircraft_engine_metrics', index=False)
    df15.to_excel(writer, sheet_name='5_aircraft_weights', index=False)
    df16.to_excel(writer, sheet_name='6_aircraft_dimensions', index=False)
    df21.to_excel(writer, sheet_name='airline_finance', index=False)
    df22.to_excel(writer, sheet_name='airline_identity', index=False)
    df23.to_excel(writer, sheet_name='airline_market', index=False)
    df31.to_excel(writer, sheet_name='airline_stock_analysis', index=False)
    df32.to_excel(writer, sheet_name='airline_stock_prices', index=False)
    df41.to_excel(writer, sheet_name='oil_prices_analysis', index=False)
    df42.to_excel(writer, sheet_name='oil_prices_main', index=False)
    df50.to_excel(writer, sheet_name='airline_fleet_cleaned', index=False)
    df60.to_excel(writer, sheet_name='airline_income_metric_new', index=False)
    df70.to_excel(writer, sheet_name='airlines_metadata_cleaned', index=False)

In [11]:
# Hər df üçün ayrı mapping lüğətləri
map12 = {
    'PERFORMANCE_RANGE_KM': 'PERF_RANGE_KM', 'PERFORMANCE_RANGE_NM': 'PERF_RANGE_NM',
    'PERFORMANCE_RANGE_MI': 'PERF_RANGE_MI', 'PERFORMANCE_LANDING_DISTANCE_M': 'PERF_LANDING_DIST_M',
    'PERFORMANCE_LANDING_DISTANCE_FT': 'PERF_LANDING_DIST_FT', 'PERFORMANCE_TAKEOFF_DISTANCE_M': 'PERF_TAKEOFF_DIST_M',
    'PERFORMANCE_TAKEOFF_DISTANCE_FT': 'PERF_TAKEOFF_DIST_FT', 'PERFORMANCE_CEILING_M': 'PERF_CEILING_M',
    'PERFORMANCE_CEILING_FT': 'PERF_CEILING_FT'
}

map13 = {
    'PERFORMANCE_APPROACH_SPEED_KMH': 'PERF_APPROACH_SPD_KMH', 'PERFORMANCE_APPROACH_SPEED_KT': 'PERF_APPROACH_SPD_KT',
    'PERFORMANCE_MAX_CRUISE_SPEED_KMH': 'PERF_MAX_CRUISE_SPD_KMH', 'PERFORMANCE_MAX_CRUISE_SPEED_KT': 'PERF_MAX_CRUISE_SPD_KT'
}

map14 = {
    'PERFORMANCE_FUEL_BURN_NM_GAL': 'PERF_FUEL_BURN_NM_GAL', 'PERFORMANCE_FUEL_BURN_KML': 'PERF_FUEL_BURN_KML',
    'PERFORMANCE_RATE_OF_CLIMB_FT_MIN': 'PERF_CLIMB_RATE_FT_MIN', 'PERFORMANCE_RATE_OF_CLIMB_MS': 'PERF_CLIMB_RATE_MS'
}

map15 = {
    'WEIGHT_MAX_TAKEOFF_WEIGHT_KG': 'WT_MAX_TAKEOFF_KG', 'WEIGHT_MAX_TAKEOFF_WEIGHT_LB': 'WT_MAX_TAKEOFF_LB',
    'WEIGHT_MAX_LANDING_WEIGHT_KG': 'WT_MAX_LANDING_KG', 'WEIGHT_MAX_LANDING_WEIGHT_LB': 'WT_MAX_LANDING_LB',
    'WEIGHT_MAX_PAYLOAD_KG': 'WT_MAX_PAYLOAD_KG', 'WEIGHT_MAX_PAYLOAD_LB': 'WT_MAX_PAYLOAD_LB',
    'WEIGHT_FUEL_CAPACITY_GAL': 'WT_FUEL_CAP_GAL', 'WEIGHT_FUEL_CAPACITY_L': 'WT_FUEL_CAP_L',
    'WEIGHT_FUEL_CAPACITY_KG': 'WT_FUEL_CAP_KG'
}

map16 = {
    'SIZE_BAGGAGE_VOLUME_FT3': 'SZ_BAGGAGE_VOL_FT3', 'SIZE_BAGGAGE_VOLUME_M3': 'SZ_BAGGAGE_VOL_M3',
    'SIZE_CABIN_HEIGHT_M': 'SZ_CABIN_HEIGHT_M', 'SIZE_CABIN_HEIGHT_FT': 'SZ_CABIN_HEIGHT_FT',
    'SIZE_CABIN_LENGTH_M': 'SZ_CABIN_LENGTH_M', 'SIZE_CABIN_LENGTH_FT': 'SZ_CABIN_LENGTH_FT',
    'SIZE_CABIN_WIDTH_M': 'SZ_CABIN_WIDTH_M', 'SIZE_CABIN_WIDTH_FT': 'SZ_CABIN_WIDTH_FT',
    'SIZE_EXTERIOR_LENGTH_M': 'SZ_EXTERIOR_LENGTH_M', 'SIZE_EXTERIOR_LENGTH_FT': 'SZ_EXTERIOR_LENGTH_FT',
    'SIZE_FUSELAGE_DIAMETER_M': 'SZ_FUSELAGE_DIA_M', 'SIZE_FUSELAGE_DIAMETER_FT': 'SZ_FUSELAGE_DIA_FT',
    'SIZE_TAIL_HEIGHT_M': 'SZ_TAIL_HEIGHT_M', 'SIZE_TAIL_HEIGHT_FT': 'SZ_TAIL_HEIGHT_FT',
    'SIZE_WING_SPAN_M': 'SZ_WING_SPAN_M', 'SIZE_WING_SPAN_FT': 'SZ_WING_SPAN_FT'
}

In [12]:
from sqlalchemy import create_engine

# Engine yaratmaq (Öz şifrəni yaz)
engine = create_engine('oracle+oracledb://AVIATION_PROJECT:12345@localhost:1521/?service_name=XEPDB1')

# Sütunları böyük hərfə çevirmək funksiyası
def prepare_df(df, mapping=None):
    df.columns = [c.upper() for c in df.columns]
    if mapping:
        df = df.rename(columns=mapping)
    return df

try:
    # df11 - AC_BASIC (Xüsusi mapping yoxdur, sadəcə böyük hərf)
    prepare_df(df11).to_sql('ac_basic', engine, if_exists='append', index=False)
    print("df11 yükləndi.")

    # df12 - AC_RANGE_ALT
    prepare_df(df12, map12).to_sql('ac_range_alt', engine, if_exists='append', index=False)
    print("df12 yükləndi.")

    # df13 - AC_SPEED
    prepare_df(df13, map13).to_sql('ac_speed', engine, if_exists='append', index=False)
    print("df13 yükləndi.")

    # df14 - AC_ENGINE_METRICS
    prepare_df(df14, map14).to_sql('ac_engine_metrics', engine, if_exists='append', index=False)
    print("df14 yükləndi.")

    # df15 - AC_WEIGHTS
    prepare_df(df15, map15).to_sql('ac_weights', engine, if_exists='append', index=False)
    print("df15 yükləndi.")

    # df16 - AC_DIMENSIONS
    prepare_df(df16, map16).to_sql('ac_dimensions', engine, if_exists='append', index=False)
    print("df16 yükləndi.")

    print("\n--- Bütün Aircraft Specs dataları Oracle-a uğurla köçürüldü! ---")

except Exception as e:
    print(f"Xəta baş verdi: {e}")

df11 yükləndi.
df12 yükləndi.
df13 yükləndi.
df14 yükləndi.
df15 yükləndi.
df16 yükləndi.

--- Bütün Aircraft Specs dataları Oracle-a uğurla köçürüldü! ---

In [13]:
map_finance = {
    'PROFIT_MARGINS': 'PROFIT_MARGINS',
    'OPERATING_MARGINS': 'OP_MARGINS',
    'RETURN_ON_ASSETS': 'ROA',
    'RETURN_ON_EQUITY': 'ROE',
    'DEBT_TO_EQUITY': 'DEBT_TO_EQUITY',
    'TOTAL_CASH': 'TOTAL_CASH',
    'TOTAL_DEBT': 'TOTAL_DEBT',
    'REVENUE_TTM': 'REVENUE_TTM',
    'EBITDA_TTM': 'EBITDA_TTM'
}

map_market = {
    'AIRLINE_NAME': 'AIRLINE_NAME',
    'MARKET_CAP': 'MARKET_CAP',
    'ENTERPRISE_VALUE': 'ENTERPRISE_VALUE',
    'TRAILING_PE': 'TRAILING_PE',
    'FORWARD_PE': 'FORWARD_PE',
    'PRICE_TO_BOOK': 'PRICE_TO_BOOK'
}

In [14]:
try:
    # 1. AL_IDENTITY (İlk bunu yükləməliyik, çünki Primary Key buradadır)
    df22.columns = [c.upper() for c in df22.columns]
    df22.to_sql('al_identity', engine, if_exists='append', index=False)
    print("df22 (Identity) yükləndi.")

    # 2. AL_FINANCE
    df21.columns = [c.upper() for c in df21.columns]
    df21 = df21.rename(columns=map_finance)
    df21.to_sql('al_finance', engine, if_exists='append', index=False)
    print("df21 (Finance) yükləndi.")

    # 3. AL_MARKET
    df23.columns = [c.upper() for c in df23.columns]
    df23 = df23.rename(columns=map_market)
    df23.to_sql('al_market', engine, if_exists='append', index=False)
    print("df23 (Market) yükləndi.")

    print("\n--- Airline Fundamentals dataları uğurla köçürüldü! ---")

except Exception as e:
    print(f"Xəta baş verdi: {e}")

df22 (Identity) yükləndi.
df21 (Finance) yükləndi.
df23 (Market) yükləndi.

--- Airline Fundamentals dataları uğurla köçürüldü! ---

In [15]:
# df31 (Analysis) üçün mapping
map_stock_analysis = {
    'DATE': 'TRADE_DATE',
    'ROLLING_VOLATILITY_30D': 'VOLATILITY_30D'
}

# df32 (Prices) üçün mapping
map_stock_prices = {
    'DATE': 'TRADE_DATE',
    'OPEN': 'OPEN_PRICE',
    'HIGH': 'HIGH_PRICE',
    'LOW': 'LOW_PRICE',
    'CLOSE': 'CLOSE_PRICE'
}

In [16]:
try:
    # 1. df32 - AL_STOCK_PRICES yüklənməsi
    df32.columns = [c.upper() for c in df32.columns] # Sütunları böyük hərf et
    df32['DATE'] = pd.to_datetime(df32['DATE'])      # Tarix formatına çevir
    df32 = df32.rename(columns=map_stock_prices)    # Mapping tətbiq et
    
    df32.to_sql('al_stock_prices', engine, if_exists='append', index=False)
    print("df32 (Stock Prices) uğurla yükləndi.")

    # 2. df31 - AL_STOCK_ANALYSIS yüklənməsi
    df31.columns = [c.upper() for c in df31.columns] # Sütunları böyük hərf et
    df31['DATE'] = pd.to_datetime(df31['DATE'])      # Tarix formatına çevir
    df31 = df31.rename(columns=map_stock_analysis)  # Mapping tətbiq et
    
    df31.to_sql('al_stock_analysis', engine, if_exists='append', index=False)
    print("df31 (Stock Analysis) uğurla yükləndi.")

    print("\n--- 3-cü hissə (Stock Data) uğurla köçürüldü! ---")

except Exception as e:
    print(f"Xəta baş verdi: {e}")

df32 (Stock Prices) uğurla yükləndi.
df31 (Stock Analysis) uğurla yükləndi.

--- 3-cü hissə (Stock Data) uğurla köçürüldü! ---

In [17]:
# df41 (Oil Analysis) üçün mapping
map_oil_analysis = {
    'DATE': 'TRADE_DATE',
    'ROLLING_VOLATILITY_30D': 'VOLATILITY_30D'
}

# df42 (Oil Main) üçün mapping
map_oil_main = {
    'DATE': 'TRADE_DATE',
    'OPEN': 'OPEN_PRICE',
    'HIGH': 'HIGH_PRICE',
    'LOW': 'LOW_PRICE',
    'CLOSE': 'CLOSE_PRICE'
}

In [18]:
try:
    # 1. df42 - OIL_PRICES_MAIN yüklənməsi
    df42.columns = [c.upper() for c in df42.columns]
    df42['DATE'] = pd.to_datetime(df42['DATE'])
    df42 = df42.rename(columns=map_oil_main)
    
    df42.to_sql('oil_prices_main', engine, if_exists='append', index=False)
    print("df42 (Oil Main) uğurla yükləndi.")

    # 2. df41 - OIL_PRICES_ANALYSIS yüklənməsi
    df41.columns = [c.upper() for c in df41.columns]
    df41['DATE'] = pd.to_datetime(df41['DATE'])
    df41 = df41.rename(columns=map_oil_analysis)
    
    df41.to_sql('oil_prices_analysis', engine, if_exists='append', index=False)
    print("df41 (Oil Analysis) uğurla yükləndi.")

    print("\n--- 4-cü hissə (Oil Data) uğurla köçürüldü! ---")

except Exception as e:
    print(f"Xəta baş verdi: {e}")

df42 (Oil Main) uğurla yükləndi.
df41 (Oil Analysis) uğurla yükləndi.

--- 4-cü hissə (Oil Data) uğurla köçürüldü! ---

In [19]:
# df50 (Fleet)
map_fleet = {
    'FUTURE': 'FUTURE_FLEET',
    'AVG_AGE_NUMERIC': 'AVG_AGE'
}

# df60 (Income)
map_income = {
    'NET_INCOME': 'NET_INC',
    'OPERATING_EXPENSE': 'OP_EXPENSE',
    'OPERATING_INCOME': 'OP_INCOME'
}

# df70 (Metadata)
map_metadata = {
    'NAME': 'AIRLINE_NAME',
    'ACTIVE': 'IS_ACTIVE'
}

In [22]:
from sqlalchemy import create_engine

# Engine yaratmaq (Öz şifrəni yaz)
engine = create_engine('oracle+oracledb://AVIATION_PROJECT:12345@localhost:1521/?service_name=XEPDB1')

# Sütunları böyük hərfə çevirmək funksiyası
def prepare_df(df, mapping=None):
    df.columns = [c.upper() for c in df.columns]
    if mapping:
        df = df.rename(columns=mapping)
    return df


try:
    # 3. df70 - AL_METADATA
    df70.columns = [c.upper() for c in df70.columns]
    df70 = df70.rename(columns=map_metadata)
    df70.to_sql('al_metadata', engine, if_exists='append', index=False)
    print("df70 (Metadata) yükləndi.")

    # 1. df50 - AL_FLEET
    df50.columns = [c.upper() for c in df50.columns]
    df50 = df50.rename(columns=map_fleet)
    df50.to_sql('al_fleet', engine, if_exists='append', index=False)
    print("df50 (Fleet) yükləndi.")

    # 2. df60 - AL_INCOME_METRICS
    df60.columns = [c.upper() for c in df60.columns]
    df60['PERIOD_END'] = pd.to_datetime(df60['PERIOD_END']) # Tarixə çevir
    df60 = df60.rename(columns=map_income)
    df60.to_sql('al_income_metrics', engine, if_exists='append', index=False)
    print("df60 (Income Metrics) yükləndi.")

    print("\n--- BÜTÜN LAYİHƏ DATALARI ORACLE-A UĞURLA KÖÇÜRÜLDÜ! ---")

except Exception as e:
    print(f"Xəta baş verdi: {e}")

df70 (Metadata) yükləndi.
Xəta baş verdi: (oracledb.exceptions.IntegrityError) ORA-02291: bütünlük kısıtlaması (AVIATION_PROJECT.FK_AL_FLEET) bozuldu - üst anahtar bulunamadı
Help: https://docs.oracle.com/error-help/db/ora-02291/
[SQL: INSERT INTO al_fleet ("AIRLINE_NAME", "AIRCRAFT_TYPE", "IN_SERVICE", "PARKED", "TOTAL_CURRENT", "FUTURE_FLEET", "HISTORIC", "TOTAL_ALL_TIME", "AVG_AGE") VALUES (:AIRLINE_NAME, :AIRCRAFT_TYPE, :IN_SERVICE, :PARKED, :TOTAL_CURRENT, :FUTURE_FLEET, :HISTORIC, :TOTAL_ALL_TIME, :AVG_AGE)]
[parameters: [{'AIRLINE_NAME': 'Qatar Airways', 'AIRCRAFT_TYPE': 'Airbus A300', 'IN_SERVICE': 0, 'PARKED': 0, 'TOTAL_CURRENT': 0, 'FUTURE_FLEET': 0, 'HISTORIC': 10, 'TOTAL_ALL_TIME': 10, 'AVG_AGE': None}, {'AIRLINE_NAME': 'Qatar Airways', 'AIRCRAFT_TYPE': 'Airbus A310', 'IN_SERVICE': 0, 'PARKED': 0, 'TOTAL_CURRENT': 0, 'FUTURE_FLEET': 0, 'HISTORIC': 2, 'TOTAL_ALL_TIME': 2, 'AVG_AGE': None}, {'AIRLINE_NAME': 'Qatar Airways', 'AIRCRAFT_TYPE': 'Airbus A319', 'IN_SERVICE': 0, 'PARKED': 0, 'TOTAL_CURRENT': 0, 'FUTURE_FLEET': 0, 'HISTORIC': 3, 'TOTAL_ALL_TIME': 3, 'AVG_AGE': None}, {'AIRLINE_NAME': 'Qatar Airways', 'AIRCRAFT_TYPE': 'Airbus A320', 'IN_SERVICE': 27, 'PARKED': 0, 'TOTAL_CURRENT': 27, 'FUTURE_FLEET': 0, 'HISTORIC': 18, 'TOTAL_ALL_TIME': 45, 'AVG_AGE': 13.6}, {'AIRLINE_NAME': 'Qatar Airways', 'AIRCRAFT_TYPE': 'Airbus A321', 'IN_SERVICE': 6, 'PARKED': 0, 'TOTAL_CURRENT': 6, 'FUTURE_FLEET': 0, 'HISTORIC': 12, 'TOTAL_ALL_TIME': 18, 'AVG_AGE': 0.4}, {'AIRLINE_NAME': 'Qatar Airways', 'AIRCRAFT_TYPE': 'Airbus A330', 'IN_SERVICE': 13, 'PARKED': 2, 'TOTAL_CURRENT': 15, 'FUTURE_FLEET': 1, 'HISTORIC': 30, 'TOTAL_ALL_TIME': 46, 'AVG_AGE': 17.0}, {'AIRLINE_NAME': 'Qatar Airways', 'AIRCRAFT_TYPE': 'Airbus A340', 'IN_SERVICE': 0, 'PARKED': 0, 'TOTAL_CURRENT': 0, 'FUTURE_FLEET': 0, 'HISTORIC': 4, 'TOTAL_ALL_TIME': 4, 'AVG_AGE': None}, {'AIRLINE_NAME': 'Qatar Airways', 'AIRCRAFT_TYPE': 'Airbus A350 XWB', 'IN_SERVICE': 60, 'PARKED': 2, 'TOTAL_CURRENT': 62, 'FUTURE_FLEET': 2, 'HISTORIC': 7, 'TOTAL_ALL_TIME': 71, 'AVG_AGE': 7.3}  ... displaying 10 of 613 total bound parameter sets ...  {'AIRLINE_NAME': 'AZAL Azerbaijan Airlines', 'AIRCRAFT_TYPE': 'Embraer ERJ-170', 'IN_SERVICE': 0, 'PARKED': 0, 'TOTAL_CURRENT': 0, 'FUTURE_FLEET': 0, 'HISTORIC': 1, 'TOTAL_ALL_TIME': 1, 'AVG_AGE': None}, {'AIRLINE_NAME': 'AZAL Azerbaijan Airlines', 'AIRCRAFT_TYPE': 'Embraer ERJ-190', 'IN_SERVICE': 7, 'PARKED': 0, 'TOTAL_CURRENT': 7, 'FUTURE_FLEET': 0, 'HISTORIC': 1, 'TOTAL_ALL_TIME': 8, 'AVG_AGE': 10.0}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [23]:
from sqlalchemy import create_engine

# Engine yaratmaq (Öz şifrəni yaz)
engine = create_engine('oracle+oracledb://AVIATION_PROJECT:12345@localhost:1521/?service_name=XEPDB1')

# Sütunları böyük hərfə çevirmək funksiyası
def prepare_df(df, mapping=None):
    df.columns = [c.upper() for c in df.columns]
    if mapping:
        df = df.rename(columns=mapping)
    return df


try:

    # 2. df60 - AL_INCOME_METRICS
    df60.columns = [c.upper() for c in df60.columns]
    df60['PERIOD_END'] = pd.to_datetime(df60['PERIOD_END']) # Tarixə çevir
    df60 = df60.rename(columns=map_income)
    df60.to_sql('al_income_metrics', engine, if_exists='append', index=False)
    print("df60 (Income Metrics) yükləndi.")

    print("\n--- BÜTÜN LAYİHƏ DATALARI ORACLE-A UĞURLA KÖÇÜRÜLDÜ! ---")

except Exception as e:
    print(f"Xəta baş verdi: {e}")

df60 (Income Metrics) yükləndi.

--- BÜTÜN LAYİHƏ DATALARI ORACLE-A UĞURLA KÖÇÜRÜLDÜ! ---

In [24]:
from sqlalchemy import create_engine

# Engine yaratmaq (Öz şifrəni yaz)
engine = create_engine('oracle+oracledb://AVIATION_PROJECT:12345@localhost:1521/?service_name=XEPDB1')

# Sütunları böyük hərfə çevirmək funksiyası
def prepare_df(df, mapping=None):
    df.columns = [c.upper() for c in df.columns]
    if mapping:
        df = df.rename(columns=mapping)
    return df


try:

    # 1. df50 - AL_FLEET
    df50.columns = [c.upper() for c in df50.columns]
    df50 = df50.rename(columns=map_fleet)
    df50.to_sql('al_fleet', engine, if_exists='append', index=False)
    print("df50 (Fleet) yükləndi.")


    print("\n--- BÜTÜN LAYİHƏ DATALARI ORACLE-A UĞURLA KÖÇÜRÜLDÜ! ---")

except Exception as e:
    print(f"Xəta baş verdi: {e}")

Xəta baş verdi: (oracledb.exceptions.IntegrityError) ORA-02291: bütünlük kısıtlaması (AVIATION_PROJECT.FK_AL_FLEET) bozuldu - üst anahtar bulunamadı
Help: https://docs.oracle.com/error-help/db/ora-02291/
[SQL: INSERT INTO al_fleet ("AIRLINE_NAME", "AIRCRAFT_TYPE", "IN_SERVICE", "PARKED", "TOTAL_CURRENT", "FUTURE_FLEET", "HISTORIC", "TOTAL_ALL_TIME", "AVG_AGE") VALUES (:AIRLINE_NAME, :AIRCRAFT_TYPE, :IN_SERVICE, :PARKED, :TOTAL_CURRENT, :FUTURE_FLEET, :HISTORIC, :TOTAL_ALL_TIME, :AVG_AGE)]
[parameters: [{'AIRLINE_NAME': 'Qatar Airways', 'AIRCRAFT_TYPE': 'Airbus A300', 'IN_SERVICE': 0, 'PARKED': 0, 'TOTAL_CURRENT': 0, 'FUTURE_FLEET': 0, 'HISTORIC': 10, 'TOTAL_ALL_TIME': 10, 'AVG_AGE': None}, {'AIRLINE_NAME': 'Qatar Airways', 'AIRCRAFT_TYPE': 'Airbus A310', 'IN_SERVICE': 0, 'PARKED': 0, 'TOTAL_CURRENT': 0, 'FUTURE_FLEET': 0, 'HISTORIC': 2, 'TOTAL_ALL_TIME': 2, 'AVG_AGE': None}, {'AIRLINE_NAME': 'Qatar Airways', 'AIRCRAFT_TYPE': 'Airbus A319', 'IN_SERVICE': 0, 'PARKED': 0, 'TOTAL_CURRENT': 0, 'FUTURE_FLEET': 0, 'HISTORIC': 3, 'TOTAL_ALL_TIME': 3, 'AVG_AGE': None}, {'AIRLINE_NAME': 'Qatar Airways', 'AIRCRAFT_TYPE': 'Airbus A320', 'IN_SERVICE': 27, 'PARKED': 0, 'TOTAL_CURRENT': 27, 'FUTURE_FLEET': 0, 'HISTORIC': 18, 'TOTAL_ALL_TIME': 45, 'AVG_AGE': 13.6}, {'AIRLINE_NAME': 'Qatar Airways', 'AIRCRAFT_TYPE': 'Airbus A321', 'IN_SERVICE': 6, 'PARKED': 0, 'TOTAL_CURRENT': 6, 'FUTURE_FLEET': 0, 'HISTORIC': 12, 'TOTAL_ALL_TIME': 18, 'AVG_AGE': 0.4}, {'AIRLINE_NAME': 'Qatar Airways', 'AIRCRAFT_TYPE': 'Airbus A330', 'IN_SERVICE': 13, 'PARKED': 2, 'TOTAL_CURRENT': 15, 'FUTURE_FLEET': 1, 'HISTORIC': 30, 'TOTAL_ALL_TIME': 46, 'AVG_AGE': 17.0}, {'AIRLINE_NAME': 'Qatar Airways', 'AIRCRAFT_TYPE': 'Airbus A340', 'IN_SERVICE': 0, 'PARKED': 0, 'TOTAL_CURRENT': 0, 'FUTURE_FLEET': 0, 'HISTORIC': 4, 'TOTAL_ALL_TIME': 4, 'AVG_AGE': None}, {'AIRLINE_NAME': 'Qatar Airways', 'AIRCRAFT_TYPE': 'Airbus A350 XWB', 'IN_SERVICE': 60, 'PARKED': 2, 'TOTAL_CURRENT': 62, 'FUTURE_FLEET': 2, 'HISTORIC': 7, 'TOTAL_ALL_TIME': 71, 'AVG_AGE': 7.3}  ... displaying 10 of 613 total bound parameter sets ...  {'AIRLINE_NAME': 'AZAL Azerbaijan Airlines', 'AIRCRAFT_TYPE': 'Embraer ERJ-170', 'IN_SERVICE': 0, 'PARKED': 0, 'TOTAL_CURRENT': 0, 'FUTURE_FLEET': 0, 'HISTORIC': 1, 'TOTAL_ALL_TIME': 1, 'AVG_AGE': None}, {'AIRLINE_NAME': 'AZAL Azerbaijan Airlines', 'AIRCRAFT_TYPE': 'Embraer ERJ-190', 'IN_SERVICE': 7, 'PARKED': 0, 'TOTAL_CURRENT': 7, 'FUTURE_FLEET': 0, 'HISTORIC': 1, 'TOTAL_ALL_TIME': 8, 'AVG_AGE': 10.0}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)